name: Android Build Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout secrets
      uses: actions/checkout@v4
      with:
        repository: stock-inc/dysnomia-android-secrets
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Debug
      run: |
        pwd
        ls
        tree
    - uses: actions/checkout@v4
    - name: Debug
      run: |
        pwd
        ls
        tree
